# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U86pmF0k-QCDg0Tn6G90CnWMrMmsyu3P
"""

def minimum(arr):
    """
    Finds the minimum element in an array.

    Args:
        arr: A list of integers.

    Returns:
        The minimum element in the array.
    """
    # TODO
    if len(arr) == 0:
        # retrns None is the array is empty
        return None
    min_elem  = arr[0]
    # considering the first element as the minimum initially
    if len(arr) == 1:
        # if there's a single element we return the element
        return min_elem
    else:
        # else we loop throught the rest of the array
        for a in arr[1:]:
            if min_elem>a:
                # if the elmnt is smaller than the min_elem, we assign it to min_elem
                min_elem=a
        return min_elem

# Test
array = [4, 7, 1, 3, 9, 1]
print("minimum element:", minimum(array))