# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXViHTatWMii_SK8siow7Ja432a4rzN-
"""

def second_minimum(arr):
    """
    Finds the second minimum element in an array.

    Args:
        arr: A list of integers.

    Returns:
        The second minimum element in the array.
    """
    # TODO
    if len(arr) < 2:
        # if the size of the array is less than 2, then there wont a second min element
        return None
    a1 = arr[0]
    a2 = arr[1]
    if a1>a2:
        a1, a2 = a2, a1
        # swapping the element to make sure that the smallest element is a1 and a2 is the second smallest
    if len(arr) == 2:
        if a1==a2:
            # if they are equal we return None
            return None
        else:
            # else we return a2
            return a2
    
    for a in arr[2:]:
        # we loop throught the rest of the array
        if a2>a:
            # if the element is less than a2
            # we check for the following cases
            if a1>a:
                # if the element is smaller than a1 that means it could be the minimum element
                # so, we reassign th values
                a2=a1
                a1=a
            elif a1==a:
                # if the smallest element is equal to a1, we continue as it is just an extra element
                continue
            else:
                # else we just assign it to a2
                a2=a
    if a2==a1:
        # if the elements are still smae
        # i.e., all the elements of the list are the same
        # we return None
        return None
    return a2

# Test
array = [4, 7, 1, 3, 9, 1]
print("Second minimum element:", second_minimum(array))